# Build settings
gems:
  - jemoji
  - jekyll-paginate
  - jekyll-sitemap

# Site settings
title: "Alvaro Inckot"
description: > # this means to ignore newlines until "email:"
  Building the cloud from sandâ€”one layer at a time.

email: gmail@alvaroinckot.com
#blog logo
logo: "/assets/images/author.jpeg"
logo_icon: "/assets/images/home_icon.png"
float_logo: true # true, false (default)

# blog cover
cover: "/assets/images/background.png"

name: 'Alvaro Inckot'
author: 'Alvaro Inckot'
author_image: "/assets/images/author.jpeg"

paginate:	10

url: "https://www.alvaroinckot.com" # the base hostname & protocol for your site
baseurl: ""
#used to display twitter cards
twitter_handle: '@alvaroinckot'

#fill in disqus shortname to use disqus
#disqus: disqus-shortname

google_analytics: G-GFZDFDDGGN

# social icons and sharing options
social:
  - icon:	twitter
    url:	https://x.com/alvaroinckot
    desc: Follow me on X
    share_url: http://twitter.com/share
    share_title: ?text=
    share_link: "&amp;url="

#   - icon:	facebook
#     url:	https://facebook.com/???
#    desc: Connect with me facebook
#    share_url: https://www.facebook.com/sharer.php
#    share_title: ?t=
#    share_link: "&amp;u="

  - icon:	github
    url:	https://github.com/alvaroinckot
    desc:	Fork me on github
    share_url:
    share_title:
    share_link:

  - icon:	linkedin
    url:	https://www.linkedin.com/in/alvaroinckot/
    desc:	FFollow me on linkedin
    share_url:
    share_title:
    share_link:

# - icon:	google-plus
#    url:	https://google.com/???
#    desc:	Add me on google+
#    share_url:
#    share_title:
#    share_link:
